### ISSUE TITLE
Questions on the harness generator

### ISSUE THREAD

**Issue by De3mond** [FoRTE-Research/winfuzz-winnie#1]
I set the harness generator as the README guided and worked on `7z` with it. I found a question on START_FUNCTION in the process, as I didn't find any info about start_function in `drltrace.PID.log`, also found nothing in `memdump` folder. I tried to use IDA PRO to get export func in 7z.dll and use it as start_function, but only find errors below. I'll attach my output info with the issue.
```
# Run harness synthesizer on single trace which starts from START_FUNCTION(...)
python3 synthesizer.py harness -t cor1_1/drltrace.PID.log -d cor1_1/memdump -s START_FUNCTION

Traceback (most recent call last):
  File "C:\Users\Desmond\Desktop\winnie\harnessgen\synthesizer.py", line 147, in <module>
    main()
  File "C:\Users\Desmond\Desktop\winnie\harnessgen\synthesizer.py", line 135, in main
    syn = SingleSynthesizer(args.trace_file, args.dump_dir,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Desmond\Desktop\winnie\harnessgen\common.py", line 474, in __init__
    self.start_cid, self.trace_tid = ret_start_point(self.trace_pn, self.start_func.encode())
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Desmond\Desktop\winnie\harnessgen\common.py", line 37, in ret_start_point
    raise Exception("Cannot find the starting function from the trace file")
Exception: Cannot find the starting function from the trace file
```
[out.zip](https://github.com/user-attachments/files/17218830/out.zip)

**Comment by De3mond** [comment]
[out.zip](https://github.com/user-attachments/files/17218836/out.zip)

**Comment by leocstone** [comment]
I believe START_FUNCTION is supposed to be a placeholder for the actual function that you want the harness generator to start from in the trace (look at lines 15 and 16 of `synthesizer.py`), so you would need to pick one of the function names that appears in the trace, e.g. `CreateObject`.

Unfortunately, I don't have an IDA pro license, so I have never actually used the Winnie harness generator. To fuzz `7z`, I would try writing a harness manually based off of the examples in [`harness-samples`](harness-samples). Essentially, you're going to write a DLL that uses `GetProcAddress` to find the address of the functions from the 7z DLL that you want to use, and then piece together a function that exercises the parsing code.
